#!/bin/bash
# Helper script to pull environment variables from Vercel

echo "🔐 Setting up environment variables from Vercel..."
echo ""
echo "Option 1: Pull from Vercel CLI (recommended)"
echo "  Run: vercel login"
echo "  Then: vercel env pull .env.local"
echo ""
echo "Option 2: Manual setup from Vercel Dashboard"
echo "  1. Go to: https://vercel.com/dashboard"
echo "  2. Select your colorwizard project"
echo "  3. Go to Settings → Environment Variables"
echo "  4. Copy each variable value"
echo "  5. Paste into .env.local file"
echo ""
echo "Required variables:"
echo "  Firebase:"
echo "    - NEXT_PUBLIC_FIREBASE_API_KEY"
echo "    - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
echo "    - NEXT_PUBLIC_FIREBASE_PROJECT_ID"
echo "    - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
echo "    - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
echo "    - NEXT_PUBLIC_FIREBASE_APP_ID"
echo ""
echo "  Stripe:"
echo "    - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
echo "    - STRIPE_SECRET_KEY"
echo "    - NEXT_PUBLIC_STRIPE_LIFETIME_PRODUCT_ID"
echo "    - NEXT_PUBLIC_STRIPE_LIFETIME_PRICE_ID"
echo "    - STRIPE_WEBHOOK_SECRET"
echo ""
echo "  Email (optional):"
echo "    - RESEND_API_KEY (or SENDGRID_API_KEY)"
echo ""
echo "  App:"
echo "    - NEXT_PUBLIC_APP_URL (use http://localhost:3000 for local dev)"
echo ""
